return {
  {
    id = "modern_start_menu_ui",
    key = "start_menu",
    name = "Modern Start Menu",
    short = "START",
    version = "0.1.21.1",
    installOrder = 5,
    files = { "main.lua", "screen.lua", "settings.lua", "icons.lua" },
    assets = { "assets/start_menu_icons.png" },
    legacyExtras = { "icons", "icon_order" },
  },
  {
    id = "modern_party_ui",
    key = "party",
    aspectRatio = true,
    name = "Modern Party UI",
    short = "PARTY",
    version = "0.4.13",
    installOrder = 3,
    files = {
      "main.lua", "screen.lua", "summary.lua", "party_tools.lua",
      "ribbons.lua", "gen2.lua",
    },
  },
  {
    id = "modern_bag_ui",
    key = "bag",
    aspectRatio = true,
    name = "Modern Bag UI",
    short = "BAG",
    version = "0.6.3",
    installOrder = 1,
    files = { "main.lua", "screen.lua", "inventory.lua", "gen2.lua", "gen2_presentation.lua", "pockets.lua", "sorting.lua" },
    legacyExtras = { "pocket_order" },
    assets = { "assets/classic_bag_pockets.png" },
  },
  {
    id = "modern_pc_ui",
    key = "pc",
    aspectRatio = true,
    name = "Modern PC UI",
    short = "PC",
    version = "0.6.4",
    installOrder = 6,
    files = { "main.lua", "screen.lua", "gen2.lua", "batch.lua", "gen2_portrait_cutouts.lua", "gen2_catch_storage.lua" },
  },
  {
    id = "modern_pokedex_ui",
    key = "pokedex",
    aspectRatio = true,
    name = "Modern Pokedex UI",
    short = "POKEDEX",
    version = "0.2.15",
    installOrder = 7,
    files = { "main.lua", "screen.lua", "locations.lua", "gen2.lua", "gen2_presentation.lua", "gen2_portrait_cutouts.lua" },
  },
  {
    id = "battle_info_hud",
    key = "battle_hud",
    aspectRatio = true,
    name = "Battle Info HUD",
    short = "BATTLE HUD",
    version = "0.10.2.5",
    installOrder = 2,
    enabledOption = "enabled",
    files = { "main.lua", "hud.lua", "meters.lua", "gen2.lua" },
  },
  {
    id = "typed_move_colors",
    key = "move_colors",
    name = "Typed Move Colors",
    short = "MOVE COLORS",
    version = "0.5.2.1",
    installOrder = 4,
    files = { "main.lua", "ui.lua", "gen2.lua", "colored_pokeballs.lua",
      "colored_pokemoves.lua" },
  },
  {
    id = "unlimited_pp",
    key = "qol",
    name = "Quality of Life",
    short = "QOL",
    version = "0.1.2",
    installOrder = 8,
    defaultEnabled = true,
    bulkUI = false,
    files = { "main.lua", "secret_mew.lua", "all_pkmn_gen1.lua", "force_crystal.lua",
      "catch_rate.lua" },
    assets = { "assets/sparkle.png" },
  },
  {
    id = "controller_rumble",
    key = "rumble",
    name = "Controller Rumble",
    short = "CONT.RUMBLE",
    version = "1.0.3",
    installOrder = 9,
    defaultEnabled = true,
    bulkUI = false,
    files = {
      "main.lua",
      "lib/Settings.lua",
      "lib/Rumble.lua",
      "lib/ShakeSync.lua",
      "lib/Extras.lua",
      "lib/MenuRumble.lua",
      "lib/HpRumble.lua",
      "lib/ExtraEvents.lua",
      "lib/OptionsScreen.lua",
    },
  },
  {
    id = "pokemoves",
    key = "pokemoves",
    name = "PokeMoves",
    short = "POKEMOVES",
    version = "0.1.0",
    installOrder = 10,
    defaultEnabled = true,
    bulkUI = false,
    files = { "main.lua" },
  },
  {
    id = "full_control",
    key = "fullctl",
    name = "Full Control",
    short = "FULL CONTROL",
    version = "1.0.0",
    installOrder = 11,
    defaultEnabled = true,
    bulkUI = false,
    files = { "main.lua" },
  },
  {
    id = "steel_typing",
    key = "steel",
    name = "Steel/Fairy and Typing Charts",
    short = "STEEL/FAIRY",
    version = "2.0.1",
    installOrder = 12,
    defaultEnabled = true,
    bulkUI = false,
    files = { "main.lua" },
  },
  {
    id = "crystal_animated_sprites_with_shiny_visuals",
    key = "crystal",
    name = "Crystal Animated Sprites",
    short = "CRYSTAL",
    version = "2.0.3",
    installOrder = 13,
    defaultEnabled = true,
    bulkUI = false,
    files = {
      "main.lua", "vendor.lua", "options_screen.lua",
      "species_map.lua", "animation_data.lua", "dimensions.lua",
    },
  },
}
